//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\MiniServerR2\\F\\Media\\Immagini\\Bugghina")]
        public string Folder {
            get {
                return ((string)(this["Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>bda11d91-7ade-4da1-855d-24adfe39d174</string>
  <string>460ad6f3-8216-469f-9b1c-52cffa5d812c</string>
  <string>3ace31a2-1482-4062-91fc-a3d7df4059aa</string>
  <string>79a2f60d-54e1-4fcd-b087-0916f1c524fc</string>
  <string>293340c9-650e-4dd7-9e6e-8bda5cf4a23b</string>
  <string>1e1db4ce-373b-4dac-9756-7b3d864fe9c9</string>
  <string>26e94273-d9c5-43f0-a6ca-036048251040</string>
  <string>2194fc4e-efc5-4c87-b571-bbd02dd54e6c</string>
  <string>c87f678a-eb28-4880-93bb-63214212c354</string>
  <string>918704ec-4811-45b6-a169-16bae3df69a8</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ApiKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApiKey"]));
            }
        }
    }
}
