//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCControlsToolkit.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCControlsToolkit.Controls.ControlsResources", typeof(ControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This overlaod of Date can not be used when date is displayed with a calendar.
        /// </summary>
        public static string DateTimeInput_Calendar {
            get {
                return ResourceManager.GetString("DateTimeInput_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This overlaod of Date can not be used when date is displayed with DropDowns.
        /// </summary>
        public static string DateTimeInput_Combo {
            get {
                return ResourceManager.GetString("DateTimeInput_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Selection.
        /// </summary>
        public static string DualSelect_MoveAllLeft {
            get {
                return ResourceManager.GetString("DualSelect_MoveAllLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string DualSelect_MoveAllRight {
            get {
                return ResourceManager.GetString("DualSelect_MoveAllRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string DualSelect_MoveDown {
            get {
                return ResourceManager.GetString("DualSelect_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        public static string DualSelect_MoveLeft {
            get {
                return ResourceManager.GetString("DualSelect_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        public static string DualSelect_MoveRight {
            get {
                return ResourceManager.GetString("DualSelect_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string DualSelect_MoveUp {
            get {
                return ResourceManager.GetString("DualSelect_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string FilterCondition_Contains {
            get {
                return ResourceManager.GetString("FilterCondition_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string FilterCondition_EndsWith {
            get {
                return ResourceManager.GetString("FilterCondition_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        public static string FilterCondition_Equal {
            get {
                return ResourceManager.GetString("FilterCondition_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string FilterCondition_GreaterThan {
            get {
                return ResourceManager.GetString("FilterCondition_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal to.
        /// </summary>
        public static string FilterCondition_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("FilterCondition_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is contained in.
        /// </summary>
        public static string FilterCondition_IsContainedIn {
            get {
                return ResourceManager.GetString("FilterCondition_IsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string FilterCondition_LessThan {
            get {
                return ResourceManager.GetString("FilterCondition_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal to.
        /// </summary>
        public static string FilterCondition_LessThanOrEqual {
            get {
                return ResourceManager.GetString("FilterCondition_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        public static string FilterCondition_NotEqual {
            get {
                return ResourceManager.GetString("FilterCondition_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string FilterCondition_StartsWith {
            get {
                return ResourceManager.GetString("FilterCondition_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Item_Delete {
            get {
                return ResourceManager.GetString("Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Item.
        /// </summary>
        public static string Item_Deleted {
            get {
                return ResourceManager.GetString("Item_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Item_Edit {
            get {
                return ResourceManager.GetString("Item_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Item_Insert {
            get {
                return ResourceManager.GetString("Item_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Row.
        /// </summary>
        public static string Item_ResetRow {
            get {
                return ResourceManager.GetString("Item_ResetRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undelete.
        /// </summary>
        public static string Item_Undelete {
            get {
                return ResourceManager.GetString("Item_Undelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Change.
        /// </summary>
        public static string Item_UndoChange {
            get {
                return ResourceManager.GetString("Item_UndoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For deletable enumerables {0} is required to implement IUpdateDisplay .
        /// </summary>
        public static string IUpdateDisplayNotImplemented {
            get {
                return ResourceManager.GetString("IUpdateDisplayNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not assignable to {1}.
        /// </summary>
        public static string NotCompatibleTypes {
            get {
                return ResourceManager.GetString("NotCompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only IEnumerable that can accept a List .
        /// </summary>
        public static string OnlyListForUpdatableEnumerable {
            get {
                return ResourceManager.GetString("OnlyListForUpdatableEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string Page_First {
            get {
                return ResourceManager.GetString("Page_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string Page_GoTo {
            get {
                return ResourceManager.GetString("Page_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string Page_Last {
            get {
                return ResourceManager.GetString("Page_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string Page_Next {
            get {
                return ResourceManager.GetString("Page_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string Page_Prev {
            get {
                return ResourceManager.GetString("Page_Prev", resourceCulture);
            }
        }
    }
}
