//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCControlsToolkit.DataAnnotations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnnotationsRsources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnnotationsRsources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCControlsToolkit.DataAnnotations.AnnotationsRsources", typeof(AnnotationsRsources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Limits of DateRangeAttribute have invalid format.
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateRangeAtrribute can be applied only to DateTime or Nullable&lt;DateTime&gt; properties.
        /// </summary>
        internal static string InvalidDateRangeApplication {
            get {
                return ResourceManager.GetString("InvalidDateRangeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DynamicRangeAttribute has been applied to an unsopported type.
        /// </summary>
        internal static string InvalidDynamicRangeApplication {
            get {
                return ResourceManager.GetString("InvalidDynamicRangeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Limits of DynamicRangeAttribute have invalid format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic minimum delay is invalid.
        /// </summary>
        internal static string InvalidLowerDynamicDelay {
            get {
                return ResourceManager.GetString("InvalidLowerDynamicDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic minimum is invalid .
        /// </summary>
        internal static string InvalidLowerDynamicRange {
            get {
                return ResourceManager.GetString("InvalidLowerDynamicRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic maximum delay is invalid.
        /// </summary>
        internal static string InvalidUpperDynamicDelay {
            get {
                return ResourceManager.GetString("InvalidUpperDynamicDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dynamic maximum is invalid .
        /// </summary>
        internal static string InvalidUpperDynamicRange {
            get {
                return ResourceManager.GetString("InvalidUpperDynamicRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not in the required range.
        /// </summary>
        internal static string StandardError {
            get {
                return ResourceManager.GetString("StandardError", resourceCulture);
            }
        }
    }
}
